name: Custom IPL
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev
    steps:
      - name: Dependencies
        run: |
          apk add clang automake autoconf zlib-dev python3 py3-pycryptodomex py3-ecdsa zip curl unzip sudo

      - name: Cloning and Building lastest pspsdk
        run: | 
          git clone https://github.com/pspdev/pspsdk

      - name: Bootstrap sdk and build
        working-directory: pspsdk
        run: |
          bash ./bootstrap
          ./configure
          make
          make install

      - name: ya2d via psp-pacman
        run: |
          psp-pacman -Syyu --noconfirm
          psp-pacman -S ya2d --noconfirm

      - name: Update psp-cfw-sdk
        run: curl -OJL "https://github.com/pspdev/psp-cfw-sdk/releases/download/latest/psp-cfw-sdk.zip"
      
      - name: Extract psp-cfw-sdk
        run: sudo unzip -o psp-cfw-sdk.zip -d /

      - name: Clone psp-dynamic-libraries
        run:  git clone https://github.com/pspdev/psp-dynamic-libraries

      - name: Build psp-dynamic-libraries
        working-directory: psp-dynamic-libraries
        run: make

      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Aquire LIBS
        run: |
          pwd
          ls
          ls ..
          ls ../..
          #cp -r ../../psp-dynamic-libraries/dist/LIBS Resources/

 #     - name: Build
 #       run:  make clean && make 

 #     - name: Compress
 #       run: |
 #         cd dist
 #         zip -r ../CustomIPL.zip .
 #     
 #     - name: Upload
 #       uses: actions/upload-artifact@v4
 #       with:
 #         name: CustomIPL-release
 #         path: CustomIPL.zip
 # release:
 #   needs: build
 #   runs-on: ubuntu-latest
 #   steps:
 #     - name: Download artifacts
 #       uses: actions/download-artifact@v8
 #       with:
 #         name: CustomIPL-release
 #         path: .
 #     - name:
 #       uses: softprops/action-gh-release@v3
 #       with:
 #         tag_name: latest
 #         name: CustomIPL pre-release
 #         prerelease: true
 #         files: CustomIPL.zip
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    

